// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB0opDwid0H_8fGFzlnkuqAkwIVpnMtpE',
    appId: '1:34097201602:web:adcbfe6edf075fb3ff165b',
    messagingSenderId: '34097201602',
    projectId: 'notesapp-b3a57',
    authDomain: 'notesapp-b3a57.firebaseapp.com',
    storageBucket: 'notesapp-b3a57.appspot.com',
    measurementId: 'G-MEMGGJW9L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFpGjk0F4_osbYkUfo7W8ztVi25j0-dm0',
    appId: '1:34097201602:android:0d3cad99f5a50d32ff165b',
    messagingSenderId: '34097201602',
    projectId: 'notesapp-b3a57',
    storageBucket: 'notesapp-b3a57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnximru1BLqtFdMdVX6KZtmXHwDGM6tf4',
    appId: '1:34097201602:ios:c61f23affb35ee20ff165b',
    messagingSenderId: '34097201602',
    projectId: 'notesapp-b3a57',
    storageBucket: 'notesapp-b3a57.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnximru1BLqtFdMdVX6KZtmXHwDGM6tf4',
    appId: '1:34097201602:ios:b25d8d3986d75534ff165b',
    messagingSenderId: '34097201602',
    projectId: 'notesapp-b3a57',
    storageBucket: 'notesapp-b3a57.appspot.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
